import React, { useEffect, useState } from 'react';
import { AutomationRule, Publication, UsageSummary } from '../types';

export const AutomationsManager: React.FC<{ automations: AutomationRule[]; onRefresh: () => Promise<void> }> = ({ automations, onRefresh }) => {
  const [usage, setUsage] = useState<UsageSummary>();
  const [publications, setPublications] = useState<Publication[]>([]);
  const [busy, setBusy] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [budget, setBudget] = useState('20');
  const [form, setForm] = useState({ name: '', niche: '', run_at: '09:00', frequency: 'Daily', language: 'Tiếng Việt' });
  const loadOps = async () => { const [u, p] = await Promise.all([fetch('/api/usage'), fetch('/api/publications')]); if (u.ok) { const data = await u.json(); setUsage(data); setBudget(String(data.monthly_budget_usd)); } if (p.ok) setPublications(await p.json()); };
  useEffect(() => { void loadOps(); }, []);
  const action = async (id: string, suffix: string, options?: RequestInit) => { setBusy(id + suffix); try { const res = await fetch(`/api/automations/${id}${suffix}`, options || { method: 'POST' }); if (!res.ok) throw new Error((await res.json()).error); await onRefresh(); await loadOps(); } catch (e) { alert((e as Error).message); } finally { setBusy(''); } };
  const create = async () => { setBusy('create'); try { const res = await fetch('/api/automations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!res.ok) throw new Error('Không tạo được lịch'); setShowForm(false); setForm({ name: '', niche: '', run_at: '09:00', frequency: 'Daily', language: 'Tiếng Việt' }); await onRefresh(); } finally { setBusy(''); } };
  return <div className="space-y-6 animate-fadeIn py-4">
    <header className="flex flex-col md:flex-row justify-between gap-4 border-b border-[#262626] pb-5"><div><h2 className="text-2xl font-bold text-white">Tự động hoá & vận hành</h2><p className="text-sm text-[#aaa2b6] mt-1">Lập lịch pipeline, kiểm soát chi phí và chuẩn bị xuất bản.</p></div><button onClick={() => setShowForm(!showForm)} className="bg-[#8B5CF6] px-5 py-2.5 rounded-lg text-white text-sm">+ Tạo lịch mới</button></header>
    <div className="grid md:grid-cols-3 gap-4">
      <Metric label="Chi phí tháng" value={`$${(usage?.total_cost_usd || 0).toFixed(2)}`} detail={`Ngân sách $${(usage?.monthly_budget_usd || 0).toFixed(2)}`} />
      <Metric label="Ngân sách còn lại" value={`$${(usage?.remaining_usd || 0).toFixed(2)}`} detail={`${(usage?.percent_used || 0).toFixed(1)}% đã dùng`} />
      <Metric label="Gói xuất bản" value={String(publications.length)} detail={`${publications.filter(p => p.status === 'PACKAGE_READY').length} sẵn sàng`} />
    </div>
    <div className="flex items-center gap-3 bg-[#141414] border border-[#262626] rounded-xl p-3"><label className="text-xs text-[#aaa2b6]">Giới hạn chi phí tháng (USD)</label><input type="number" min="0" step="1" value={budget} onChange={e=>setBudget(e.target.value)} className="bg-[#090909] border border-[#444] rounded px-3 py-1.5 text-white w-28"/><button onClick={async()=>{ await fetch('/api/usage/budget',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({monthly_budget_usd:Number(budget)})}); await loadOps(); }} className="px-3 py-1.5 bg-[#30263f] text-[#d0bcff] rounded text-xs">Lưu ngân sách</button></div>
    {showForm && <div className="bg-[#141414] border border-[#8B5CF6]/40 rounded-xl p-5 grid md:grid-cols-5 gap-3"><input placeholder="Tên lịch" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="field"/><input placeholder="Chủ đề/ngách" value={form.niche} onChange={e=>setForm({...form,niche:e.target.value})} className="field"/><select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})} className="field"><option>Daily</option><option>Twice Weekly</option><option>Weekly</option></select><input type="time" value={form.run_at} onChange={e=>setForm({...form,run_at:e.target.value})} className="field"/><button disabled={!form.name || !form.niche || busy==='create'} onClick={create} className="bg-[#8B5CF6] rounded-lg text-white disabled:opacity-40">Lưu lịch</button></div>}
    <div className="bg-[#182019] border border-[#2d5b3a] p-4 rounded-xl text-sm text-[#bde7c7]">Pipeline tự động luôn dừng ở REVIEW. Chỉ người dùng mới được duyệt và xuất bản.</div>
    <div className="space-y-4">{automations.map(rule => <div key={rule.id} className="bg-[#141414] border border-[#262626] rounded-xl p-5">
      <div className="flex flex-col lg:flex-row justify-between gap-4"><div><div className="flex gap-3 items-center"><h3 className="font-bold text-white">{rule.name}</h3><span className={rule.status==='Active'?'text-[#4edea3] text-xs':'text-[#aaa2b6] text-xs'}>{rule.status==='Active'?'ĐANG CHẠY':'TẠM DỪNG'}</span></div><p className="text-xs text-[#aaa2b6] mt-1">{rule.niche} · {rule.frequency} lúc {rule.run_at || '09:00'}</p><p className="text-xs text-[#777] mt-1">Lần tới: {rule.next_run ? new Date(rule.next_run).toLocaleString('vi-VN') : 'Chưa xếp lịch'}</p>{rule.last_error && <p className="text-xs text-red-400 mt-1">{rule.last_error}</p>}</div>
      <div className="flex gap-2"><button onClick={()=>action(rule.id,'/run')} className="px-3 py-2 bg-[#8B5CF6] rounded text-xs text-white">{busy===rule.id+'/run'?'Đang chạy…':'Chạy ngay'}</button><button onClick={()=>action(rule.id,'',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:rule.status==='Active'?'Paused':'Active'})})} className="px-3 py-2 border border-[#525252] rounded text-xs text-white">{rule.status==='Active'?'Tạm dừng':'Kích hoạt'}</button><button onClick={()=>action(rule.id,'',{method:'DELETE'})} className="px-3 py-2 border border-red-900 rounded text-xs text-red-300">Xoá</button></div></div>
      <div className="grid grid-cols-3 md:grid-cols-6 gap-2 mt-4">{[['Kịch bản',rule.auto_script],['Ảnh',rule.auto_image],['Video',rule.auto_video],['Giọng',rule.auto_voice],['Render',rule.auto_render],['Người duyệt',rule.require_review]].map(([label,on])=><div key={String(label)} className="bg-[#0e0e0e] p-2 rounded text-center text-[10px]"><span className="text-[#aaa2b6] block">{label}</span><b className={on?'text-[#4edea3]':'text-[#666]'}>{on?'BẬT':'TẮT'}</b></div>)}</div>
    </div>)}</div>
    {publications.length>0 && <section><h3 className="text-white font-bold mb-3">Lịch sử xuất bản</h3><div className="bg-[#141414] rounded-xl border border-[#262626] divide-y divide-[#262626]">{publications.slice(0,5).map(p=><div key={p.id} className="p-3 flex justify-between text-xs"><span className="text-white">{p.platform}</span><span className="text-[#4edea3]">{p.status}</span></div>)}</div></section>}
  </div>;
};

const Metric = ({label,value,detail}:{label:string,value:string,detail:string}) => <div className="bg-[#141414] border border-[#262626] rounded-xl p-4"><span className="text-xs text-[#aaa2b6]">{label}</span><strong className="block text-2xl text-white mt-1">{value}</strong><span className="text-[11px] text-[#777]">{detail}</span></div>;
